name: Deploy to Pages
on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4

            - name: Run CI inside Dev Container
              uses: devcontainers/ci@v0.3
              with:
                  configFile: .devcontainer/devcontainer.json
                  push: never
                  runCmd: |
                      set -Eeuo pipefail
                      JEKYLL_ENV=production bundle exec jekyll build -t -V
            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3

    deploy:
        needs: build
        runs-on: ubuntu-24.04-arm
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4

    # # Build job
    # build:
    #   runs-on: ubuntu-22.04
    #   steps:
    #     - name: Install plantuml
    #       run: sudo apt-get update && sudo apt-get install -y plantuml
    #     - name: Checkout
    #       uses: actions/checkout@v4
    #     - name: Setup Ruby
    #       uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
    #       with:
    #         ruby-version: '3' # Not needed with a .ruby-version file
    #         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    #         cache-version: 0 # Increment this number if you need to re-download cached gems
    #     - name: Setup Pages
    #       id: pages
    #       uses: actions/configure-pages@v4
    #     # ditaa svg 문제 때문에 로컬에서 빌드해서 올린다.
    #     # - name: Bundle install
    #     #   run: bundle install
    #     # - name: Build with Jekyll
    #     #   run: bundle exec jekyll build -t -V
    #     #   env:
    #     #     JEKYLL_ENV: production
    #     - name: Upload artifact
    #       uses: actions/upload-pages-artifact@v3
